packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  bufferutil: true
  esbuild: true
  keccak: true
  node-hid: true
  sharp: true
  unrs-resolver: true
  usb: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@polkadot-cloud/connect@2.0.0'
  - '@polkadot-cloud/connect-core@2.0.0'
  - '@polkadot-cloud/connect-ledger@2.0.0'
  - '@polkadot-cloud/connect-proxies@1.0.0'
  - '@polkadot-cloud/connect-vault@2.0.0'
  - '@polkadot-cloud/hooks@1.0.0'
  - '@polkadot-cloud/ui@1.0.0'
  - '@polkadot-cloud/util-dedot@1.0.0'
  - '@polkadot-cloud/utils@1.0.0'
patchedDependencies:
  '@dedot/api@1.4.0': patches/@dedot__api@1.4.0.patch
  '@dedot/merkleized-metadata@1.4.0': patches/@dedot__merkleized-metadata@1.4.0.patch
