packages:
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  bufferutil: true
  esbuild: true
  keccak: true
  node-hid: true
  sharp: true
  unrs-resolver: true
  usb: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@polkadot-cloud/util-dedot@0.1.0'
  - '@polkadot-cloud/hooks@0.1.0'
  - '@polkadot-cloud/ui@0.1.0'
  - '@polkadot-cloud/utils@0.4.1'
  - '@polkadot-cloud/connect-core@1.2.1'
  - '@polkadot-cloud/connect-ledger@1.3.1'
  - '@polkadot-cloud/connect-proxies@0.5.1'
  - '@polkadot-cloud/connect-vault@1.2.0'
  - '@polkadot-cloud/connect@1.2.1'
patchedDependencies:
  '@dedot/api@1.4.0': patches/@dedot__api@1.4.0.patch
